### ISSUE TITLE
TxDb from NCBI RefSeq GCF_000001405.39_GRCh38.p13 is failing

### ISSUE THREAD

**Issue by mjsteinbaugh** [Bioconductor/GenomicFeatures#26]
I'm trying to load transcript metadata for NCBI `GCF_000001405.39_GRCh38.p13` into a `TxDb` object. GenomicFeatures is currently having trouble parsing the build from RefSeq:

```r
packageVersion("GenomicFeatures")
## [1] ‘1.42.1’
library(GenomicFeatures)
file <- "ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.39_GRCh38.p13/GCF_000001405.39_GRCh38.p13_genomic.gtf.gz"
txdb <- makeTxDbFromGFF(file = file)
```

```
Import genomic features from the file as a GRanges object ... trying URL 'ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.39_GRCh38.p13/GCF_000001405.39_GRCh38.p13_genomic.gtf.gz'
Content type 'unknown' length 41463702 bytes (39.5 MB)
==================================================
OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... Warning in .get_cds_IDX(mcols0$type, mcols0$phase) :
  The "phase" metadata column contains non-NA values for features of type
  stop_codon. This information was ignored.
Calls: makeTxDbFromGFF -> makeTxDbFromGRanges -> .get_cds_IDX
Error in .make_splicings(exons, cds, stop_codons) :
  some CDS cannot be mapped to an exon
Calls: makeTxDbFromGFF -> makeTxDbFromGRanges -> .make_splicings
```

**Comment by mjsteinbaugh** [comment]
@mikelove How are you handling this inside of tximeta?

**Comment by mjsteinbaugh** [comment]
Related issue seen here https://github.com/jpromeror/EventPointer/issues/9

**Comment by mjsteinbaugh** [comment]
Following up, `GCF_000001405.39_GRCh38.p13_genomic.gff.gz` will parse successfully, so this appears to be a GTF-specific issue with RefSeq.

**Comment by mikelove** [comment]
One note about p13 and tximeta: 

Because 13 is the highest number [here](ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/vertebrate_mammalian/Homo_sapiens/all_assembly_versions/), it means that it is not a stable collection of sequences. I've had this explained to me by RefSeq maintainers, when I noticed the hash for the sequence at the p13 permalink was changing. They will continually add to p13 until p14 comes along, and only then will p13 become stable.

For this reason I don't even hash p13 because it is not a stable release. 

This is different than how other providers do releases.

**Comment by mjsteinbaugh** [comment]
Thanks @mikelove that's a really helpful tip. I wasn't aware that `GCF_000001405.39_GRCh38.p13` isn't considered stable on RefSeq, particularly it is linked as the "reference" genome. Maybe they should consider linking the reference one verison behind, so this doesn't cause more confusion in the future.

**Comment by mikelove** [comment]
Trust me that I've made that suggestion :-)

**Comment by mikelove** [comment]
To be specific, the paths under `all_assembly_versions` as I quoted above are not stable until the next version comes out. It is because those are symlinks to files that are updated continually. If instead there was a versioning system + ftp structure to navigate programmatically, then I could hash the versions as they come out.

**Comment by hpages** [comment]
It's been a long time and time heals everything, even `makeTxDbFromGFF("ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.39_GRCh38.p13/GCF_000001405.39_GRCh38.p13_genomic.gtf.gz")` :wink:
