### ISSUE TITLE
protein_coding_gene not recognized as valid gene feature

### ISSUE THREAD

**Issue by cmatKhan** [Bioconductor/GenomicFeatures#33]
This genome from fungiDB:

https://fungidb.org/fungidb/app/record/dataset/NCBITAXON_235443

uses "protein_coding_gene" one of 3 top level features in column 3 of the gff3. The others are ncRNA_gene and pseudogene.

`makeTxDbFromGff` seems to recognize ncRNA_gene and pseudogene, but does not recognize protein_coding_gene. When I substituted 'gene' for 'protein_coding_gene' in the gff, `makeTxDbFromGff` worked as expected and parsed the gff correctly.

I'm actually not sure what the generally accepted source of truth is for the feature ontology, but I use this site:

http://www.sequenceontology.org/browser/current_release/term/SO:0001217

which indicates that protein_coding_gene is a valid feature at the same level as ncRNA_gene and pseudogene.

I can see this being addressed either in the code -- by adding protein_coding_gene as a 'gene' equivalent -- or in the documentation to make it clear what the expected ontology is.

**Comment by hpages** [comment]
Good catch. The `makeTxDbFromGFF()` and `makeTxDbFromGRanges()` functions are currently using hard-coded lists of SO terms to identify features in the GFF file that are genes, transcripts, exons, and CDS. These lists can be seen with `GenomicFeatures:::.GENE_TYPES`, `GenomicFeatures:::.TX_TYPES`, `GenomicFeatures:::.EXON_TYPES`, and `GenomicFeatures:::.CDS_TYPES`, respectively.

Unfortunately these manually curated lists don't contain all possible terms, only the most frequently found ones. New terms get added as we go, on a very empirical basis. Obviously not a great approach since the process is tedious and we're likely missing terms that could already be in use in commonly found GFF files. So there's lot of room for improvement here. I wonder if we shouldn't wrap a snapshot of the Sequence Ontology in an annotation package in the same way that we do with the **GO.db** package for the Gene Ontology. I'm actually surprised that we're not already doing this. This could be used by the `makeTxDbFromGFF()`/`makeTxDbFromGRanges()` functions to recognize gene, transcript, exon, and CDS features in GFF files but I would also expect that other Bioconductor packages could benefit.

Anyways, in the meantime I've added `protein_coding_gene` + all its offspring terms to `GenomicFeatures:::.GENE_TYPES` in **GenomicFeatures** 1.45.1 (BioC devel, see commit 15f83ae19b24aa4f2988085992573566ccd78270) and in 1.44.1 (BioC release).

Best,
H.
