### ISSUE TITLE
error unknown

### ISSUE THREAD

**Issue by under-score** [Bioconductor/GenomicFeatures#41]
tried
`db <- makeFeatureDbFromUCSC(genome="hg38",tablename="ncbiRefSeq",track="NCBI RefSeq")`
got
`Error: near "'none'": syntax error`
same effect with
`UCSCFeatureDbTableSchema()`
although supported by
`supportedUCSCFeatureDbTables(genome="hg38", track="NCBI RefSeq") `

**Comment by hpages** [comment]
Why use `makeFeatureDbFromUCSC()` which is under tested, under used, and has lost its original author/maintainer, when you can use `makeTxDbFromUCSC()`:
```
txdb <- makeTxDbFromUCSC(genome="hg38",tablename="ncbiRefSeq")
txdb
# TxDb object:
# Db type: TxDb
# Supporting package: GenomicFeatures
# Data source: UCSC
# Genome: hg38
# Organism: Homo sapiens
# Taxonomy ID: 9606
# UCSC Table: ncbiRefSeq
# UCSC Track: NCBI RefSeq
# Resource URL: http://genome.ucsc.edu/
# Type of Gene ID: Entrez Gene ID
# Full dataset: yes
# miRBase build ID: NA
# Nb of transcripts: 172809
# Db created by: GenomicFeatures package from Bioconductor
# Creation time: 2022-01-19 09:10:49 -0800 (Wed, 19 Jan 2022)
# GenomicFeatures version at creation time: 1.47.6
# RSQLite version at creation time: 2.2.9
# DBSCHEMAVERSION: 1.2
```

Anyways, the `makeFeatureDbFromUCSC()` issue, which was in fact a `UCSCFeatureDbTableSchema()` issue, should now be fixed in **GenomicFeatures** 1.47.6 (BioC devel) and **GenomicFeatures** 1.46.4 (BioC release). Both versions should become available via `BiocManager::install()` in the next couple of days or so.

Note that you'll also need to specify the names of the columns containing the feature starts and ends for the above `makeFeatureDbFromUCSC()` call to work e.g.:
```
db <- makeFeatureDbFromUCSC(genome="hg38", tablename="ncbiRefSeq", track="NCBI RefSeq", chromStartCol="txStart", chromEndCol="txEnd")
```
See `?makeFeatureDbFromUCSC` for more information.

**Comment by under-score** [comment]
thank you - so I suggest to remove that function from [the docs](https://www.rdocumentation.org/packages/GenomicFeatures/versions/1.24.4/topics/makeFeatureDbFromUCSC)...

**Comment by hpages** [comment]
Done: dd8aaa67e6f3a936f4439f325512ea358d590848
