### ISSUE TITLE
`makeTxDbFromGFF` fails with (bacterial) genome GTF files from NCBI

### ISSUE THREAD

**Issue by m-jahn** [Bioconductor/GenomicFeatures#56]
Dear maintainers, I noticed recently that making a Txdb object from a GFF (or GTF) file from bacteria can be difficult.
I downloaded several genome assemblies from the NCBI genomes website, all of them the reference genomes for widely used model bacteria such as Salmonella or Bacillus. When I try to make the txdb object, the function throws the following error:

```
> GenomicFeatures::makeTxDbFromGFF(".../genomes/s_enterica/GCF_000006945.2/genomic.gtf")

Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... Error in .make_splicings(exons, cds, stop_codons) : 
  some CDS cannot be mapped to an exon
In addition: Warning message:
In .get_cds_IDX(mcols0$type, mcols0$phase) :
  The "phase" metadata column contains non-NA values for features of type
  stop_codon. This information was ignored.
```

The problem here seems that there are some underlying assumptions about the structure of genes. Bacteria don't have exons, so ideally the function should not throw an error when exon information is missing. Also, bacteria can have multiple CDS on one transcript (operon structure), I'm not sure if this is also related to the error above. I am willing to make a PR to fiy this bug if I know where to look for.

Thank you!
Michael

**Comment by hpages** [comment]
Thanks for the report.

Note that the GFF file can be imported:
```
> txdb <- makeTxDbFromGFF("GCF_000006945.2_ASM694v2_genomic.gff")
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
Warning messages:
1: In .extract_transcripts_from_GRanges(tx_IDX, gr, mcols0$type, mcols0$ID,  :
  the transcript names ("tx_name" column in the TxDb object) imported
  from the "Name" attribute are not unique
2: In makeTxDbFromGRanges(gr, metadata = metadata) :
  The following transcripts were dropped because their exon ranks could
  not be inferred (either because the exons are not on the same
  chromosome/strand or because they are not separated by introns):
  gene-STM3797A
```
TxDb objects must adhere to the genes/transcripts/exons/CDS model, so if a GFF file does not report any features of type transcript or exon  (like in the case of this file where only genes and CDS are reported), then `makeTxDbFromGFF()` will add 1 transcript and 1 exon for each gene, with coordinates that match the coordinates of the gene:
```
> columns <- c("tx_name", "gene_id", "exon_name", "exon_start", "exon_end", "cds_name", "cds_start", "cds_end")
> transcripts(txdb, columns=columns)[1:4]
GRanges object with 4 ranges and 8 metadata columns:
         seqnames    ranges strand |     tx_name         gene_id
            <Rle> <IRanges>  <Rle> | <character> <CharacterList>
  [1] NC_003197.2   190-255      + |        thrL         STM0001
  [2] NC_003197.2  325-2799      + |        thrA         STM0002
  [3] NC_003197.2 2789-3730      + |        thrB         STM0003
  [4] NC_003197.2 3722-5020      + |        thrC         STM0004
            exon_name    exon_start      exon_end        cds_name     cds_start
      <CharacterList> <IntegerList> <IntegerList> <CharacterList> <IntegerList>
  [1]     NP_459006.1           190           255     NP_459006.1           190
  [2]     NP_459007.1           337          2799     NP_459007.1           337
  [3]     NP_459008.1          2801          3730     NP_459008.1          2801
  [4]     NP_459009.1          3734          5020     NP_459009.1          3734
            cds_end
      <IntegerList>
  [1]           255
  [2]          2799
  [3]          3730
  [4]          5020
  -------
  seqinfo: 2 sequences from an unspecified genome; no seqlengths
```

About this warning produced by `makeTxDbFromGFF()` on the GFF file: "The following transcripts were dropped because their exon ranks could not be inferred etc..."
After inspection of the file, it seems that `gene-STM3797A` is the only gene in this file that is reported to have 2 CDS (all the other genes have 0 or 1 CDS):
```
NC_003197.2     RefSeq  gene    3998345 3998459 .       +       .       ID=gene-STM3797A;Dbxref=GeneID:1255322;Name=ysdA;...
NC_003197.2     RefSeq  CDS     3998345 3998436 .       +       0       ID=cds-YP_009325922.1;Parent=gene-STM3797A;Dbxref=Genbank:YP_009325922.1,GeneID:1255322;Name=YP_009325922.1;...
NC_003197.2     RefSeq  CDS     3998435 3998459 .       +       1       ID=cds-YP_009325922.1;Parent=gene-STM3797A;Dbxref=Genbank:YP_009325922.1,GeneID:1255322;Name=YP_009325922.1;...
```
The warning is admittedly confusing and should be fixed, but it seems that `makeTxDbFromGFF()` tried to rank these CDS. This usually only makes sense when a CDS is split into parts that span more than one exon, which is obviously not the case here. Instead, we are in the presence of a protein-coding transcript that encodes more than one protein, which unfortunately TxDb objects don't support at the moment. Note that this is a known limitation that was reported here Bioconductor/txdbmaker#3 a while ago.

I didn't look at why `makeTxDbFromGFF()` fails on the GTF file yet, but will try to get to this later.

Hope this helps,
H.

**Comment by m-jahn** [comment]
Thanks for your reply! I will try the GFF file instead but I remember this failed for me too. I try with the latest package versions.
I don't really understand the difference between the NCBI GFF and GTF files though, I guess both are supposed to work with the `makeTxDbFromGFF` import function? Thanks for clarification!

Michael

**Comment by m-jahn** [comment]
BTW the issue heading reads wrong, I will change it.

**Comment by m-jahn** [comment]
After testing I can confirm that Import of the NCBI GFF files works just fine. For GTF files I haven't done any further tests. From my side issue can be closed.

**Comment by hpages** [comment]
@m-jahn Thanks for the update. FYI the [upcoming **txdbmaker** package](https://github.com/Bioconductor/txdbmaker) will be able to handle this GTF file.

Cheers,
H.
