### ISSUE TITLE
coverageByTranscript, seqlevels

### ISSUE THREAD

**Issue by Roleren** [Bioconductor/GenomicFeatures#6]
We used this function extensivly in our package: https://github.com/JokingHero/ORFik

And found some scary behaviors of the seqlevels:
In our packages we made our own coverageByTranscript, which in ORFik is called 
coverageByWindow

In our version we use data.table syntax, so in this gist, we swapped this for base functions, but they are slow, 
i.g. aggregate etc, that should be swapped out. 

A list of fixes we did for consistent behavior is here:
https://gist.github.com/JokingHero/3eb1d69c7fe1adbebc2c1cabc48d8ecb

Let me know what you think.
Thank you.

**Comment by hpages** [comment]
Thanks @Roleren for the report.

I've committed a fix: ee6e87b45421f3ea943d7ba2630caf4749efac18 Let me know if you still run into problems with this.

Please not that it might take several days for GenomicFeatures 1.31.14 to propagate to the BioC 3.7 public package repositories because of other blocking issues in the package (these issues are being worked on). In the mean time, you can install this latest version directly from GitHub.

Cheers,
H.

**Comment by hpages** [comment]
Hi, did you get a chance to try this? Does it address the issue? Hopefully we can close this. Thanks!

**Comment by Roleren** [comment]
Will try tomorrow, thx.

**Comment by Roleren** [comment]
I can confirm on test data that output coverage is now correct:

Looks like it is good :)

**Comment by hpages** [comment]
OK. Thanks for confirming.
